version: '3'

name: ecfgarage
services:
  db:
    image: mysql:8.2.0-oraclelinux8
    container_name: db_garageECF
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: Garage_V_Parrot
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - ecfgarage

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin_garageECF
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - ecfgarage

  app:
    image: ecf-garage:1.0
    container_name: app_garageECF
    restart: always
    ports:
      - 8000:80
    environment:
      DATABASE_URL: mysql://root:root@db:3306/Garage_V_Parrot
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ecfgarage

volumes:
  mysql:

networks:
  ecfgarage:
